name: eda
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.4.3 #1.2.3
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - wandb=0.12.21
#  - pip:
#      - wandb==0.10.31