name: basic_cleaning
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - wandb=0.12.21
#  - pip:
#      - wandb==0.10.21
